baseURL = "https://example.org/"
languageCode = "en-us"
title = "Dayville Fire Company"
theme = "arcana"
copyright = "© 1937-2023 Dayville Fire Company. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "Official website of the Dayville Volunteer Fire Company."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/DayvilleFireCompany"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/dayvillefire"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/dayvillefire/"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""

[menu]
    [[menu.main]]
        name = "Services"
        weight = 20
    [[menu.main]]
        parent = "Services"
        name = "Drone"
        weight = 21
        url = "/services/drone/"
    [[menu.main]]
        parent = "Services"
        name = "Rehabilitation"
        weight = 22
        url = "/services/rehabilitation/"
    [[menu.main]]
        parent = "Services"
        name = "Training & Education"
        weight = 23
        url = "/services/training/"
    [[menu.main]]
        parent = "Services"
        name = "Technical Rescue"
        weight = 24
        url = "/services/technical-rescue/"
    [[menu.main]]
        parent = "Technical Rescue"
        name = "Confined Space"
        weight = 25
        url = "/services/technical-rescue/confined-space/"
    [[menu.main]]
        parent = "Technical Rescue"
        name = "Vehicle Technician"
        weight = 26
        url = "/services/technical-rescue/vehicle-technican/"

    [[menu.main]]
        name = "About"
        weight = 50
    [[menu.main]]
        parent = "About"
        name = "Our History"
        weight = 51
        url = "/about/history/"
    [[menu.main]]
        parent = "About"
        name = "Members"
        weight = 51
        url = "/about/members/"
    [[menu.main]]
        parent = "About"
        name = "Chief's Report"
        weight = 52
        url = "/about/chiefs-report/"
    [[menu.main]]
        parent = "About"
        name = "DVFC Club"
        weight = 53
        url = "/about/club/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
