baseURL = "https://dayvillefire.gov/"
languageCode = "en-us"
title = "Dayville Fire Company"
theme = [ "arcana", "hugo-chart" ]
copyright = "© 1937-2023 Dayville Fire Company. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "Official website of the Dayville Volunteer Fire Company."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/DayvilleFireCompany"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/dayvillefire"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "https://www.instagram.com/dayvillefire/"


    [params.footer]

        [[params.footer.links]]
            header = "Services"
        [[params.footer.links.links]]
            title = "EMS"
            url = "/services/emergency-medical-services/"
        [[params.footer.links.links]]
            title = "Training"
            url = "/services/training/"
        [[params.footer.links.links]]
            title = "Technical Rescue"
            url = "/services/technical-rescue/"
        [[params.footer.links.links]]
            title = "Drone"
            url = "/services/drone/"
        [[params.footer.links.links]]
            title = "Rehabilitation"
            url = "/services/rehabilitation/"

        [[params.footer.links]]
            header = "About"
        [[params.footer.links.links]]
            title = "History"
            url = "/about/history/"
        [[params.footer.links.links]]
            title = "Members"
            url = "/about/members/"
        [[params.footer.links.links]]
            title = "Companies"
            url = "/about/companies/"
        [[params.footer.links.links]]
            title = "Apparatuses"
            url = "/about/apparatuses/"
        #[[params.footer.links.links]]
        #    title = "Chief's Report"
        #    url = "/about/chiefs-report/"
        [[params.footer.links.links]]
            title = "Club"
            url = "/about/club/"
        [[params.footer.links.links]]
            title = "District"
            url = "/about/district/"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""

[menu]
    [[menu.main]]
        name = "Services"
        weight = 20
    [[menu.main]]
        parent = "Services"
        name = "EMS"
        weight = 21
        url = "/services/emergency-medical-services/"
    [[menu.main]]
        parent = "Services"
        name = "Drone"
        weight = 21
        url = "/services/drone/"
    [[menu.main]]
        parent = "Services"
        name = "Rehabilitation"
        weight = 22
        url = "/services/rehabilitation/"
    [[menu.main]]
        parent = "Services"
        name = "Training & Education"
        weight = 23
        url = "/services/training/"
    [[menu.main]]
        parent = "Services"
        name = "Technical Rescue"
        weight = 24
        url = "/services/technical-rescue/"
    [[menu.main]]
        parent = "Technical Rescue"
        name = "Confined Space"
        weight = 25
        url = "/services/technical-rescue/confined-space/"
    [[menu.main]]
        parent = "Technical Rescue"
        name = "Vehicle Technician"
        weight = 26
        url = "/services/technical-rescue/vehicle-technician/"

    [[menu.main]]
        name = "About"
        weight = 50
    [[menu.main]]
        parent = "About"
        name = "Our History"
        weight = 51
        url = "/about/history/"
    [[menu.main]]
        parent = "About"
        name = "Members"
        weight = 51
        url = "/about/members/"
    [[menu.main]]
        parent = "About"
        name = "Companies"
        weight = 52
        url = "/about/companies/"
    [[menu.main]]
        parent = "About"
        name = "Apparatuses"
        weight = 53
        url = "/about/apparatuses/"
    #[[menu.main]]
    #    parent = "About"
    #    name = "Chief's Report"
    #    weight = 54
    #    url = "/about/chiefs-report/"
    [[menu.main]]
        parent = "About"
        name = "Club"
        weight = 55
        url = "/about/club/"
    [[menu.main]]
        parent = "About"
        name = "District"
        weight = 56
        url = "/about/district/"

    [[menu.main]]
        name = "Resources"
        weight = 60
    [[menu.main]]
        parent = "Resources"
        name = "QVEC Dispatch"
        weight = 61
        url = "https://www.qvec.org/"
    [[menu.main]]
        parent = "Resources"
        name = "Fire Marshal"
        weight = 62
        url = "https://www.killingly.org/fire-marshal"
    [[menu.main]]
        parent = "Resources"
        name = "Other Departments"
        weight = 67
    [[menu.main]]
        parent = "Other Departments"
        name = "Williamsville #60"
        weight = 70
        url = "https://www.facebook.com/WilliamsvilleFireEngineCo/"
    [[menu.main]]
        parent = "Other Departments"
        name = "Danielson #61"
        weight = 71
        url = "https://danielsonfire.com"
    [[menu.main]]
        parent = "Other Departments"
        name = "Attawaugan #62"
        weight = 72
        url = "https://www.facebook.com/profile.php?id=100064783176336"
    [[menu.main]]
        parent = "Other Departments"
        name = "East Killingly #64"
        weight = 74
        url = "https://www.facebook.com/eastkillinglyfd/"
    [[menu.main]]
        parent = "Other Departments"
        name = "South Killingly #65"
        weight = 75
        url = "https://southkillinglyfire.org/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
